language:
  - go
go:
  - "1.11.x"
before_script:
  - go get -v github.com/gin-gonic/gin
script:
  - go build application.go
  - go test ./... -cover -v
  - docker build -t clients .
  - docker run -d -p 8080:8080 --name clients_container clients
  - curl http://127.0.0.1:8080/v1/1
  - docker stop clients_container
  - docker rm clients_container
  - docker rmi clients
