language:
  - go
go:
  - "1.11.x"
sudo: required
env:
  - DOCKER_COMPOSE_VERSION=1.24.0
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - go get -v github.com/gin-gonic/gin
  - go get -v github.com/lib/pq
  - go get -v github.com/jmoiron/sqlx
before_script:
  - git clone https://github.com/apmath-web/data
script:
  - go build application.go
  - go test ./... -cover -v
  - docker-compose up --build -d
  - sleep 10
  - docker-compose run migrate migrate
  - 'x=`ls data/sql | wc -l`; while [ $x -gt 0 ]; do docker-compose run migrate down; x=$(($x-1)); done'
  - docker-compose down
