language:
  - go
go:
  - "1.11.x"
before_script:
  - go get -v github.com/gin-gonic/gin
  - cd tests
  - wget https://dl.bintray.com/ptrthomas/karate/karate-0.9.0.RC2.jar
  - mv karate-0.9.0.RC2.jar karate.jar
  - cd ..
script:
  - go build application.go
  - go test ./... -cover -v
  - docker build -t clients .
  - docker run -d -p 8080:8080 --name clients_container clients
  - cd tests
  - java -jar karate.jar create-client-test.feature
  - docker stop clients_container
  - docker rm clients_container
  - docker rmi clients
