version: '2'
networks:
  bridge:
    driver: bridge
services:
  clients:
    build:
      context: .
    container_name: clients
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_HOST=database
    networks:
      - bridge
  migrate:
    image: amacneil/dbmate
    container_name: migrate
    depends_on:
      - db
    volumes:
      - ./data/sql:/db/migrations
    environment:
      - DATABASE_URL=postgresql://test:test@database:5432/test?sslmode=disable
    networks:
      - bridge
  db:
    image: postgres
    container_name: database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      - bridge
