package Domain

type ConverterInterface interface {
	FromViewModel(model ClientViewModelInterface) ClientApplicationModelInterface
	FromApplicationModel(model ClientApplicationModelInterface) ClientViewModelInterface
}
